# Generated by Django 2.2.5 on 2019-09-06 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Género o técnica empleada...', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='trabajos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('year', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Año')),
                ('website', models.URLField()),
                ('picture', models.ImageField(blank=True, upload_to='images')),
                ('fecha_publicado', models.DateField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Autor')),
                ('genero', models.ManyToManyField(help_text='Género o técnica empleada...', to='catalogo.Genero')),
            ],
        ),
    ]
