# Generated by Django 2.2.5 on 2019-09-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_pictures_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name': 'Pictures'},
        ),
        migrations.AlterModelOptions(
            name='trabajos',
            options={'verbose_name': 'Trabajos'},
        ),
    ]
