# Generated by Django 2.2.5 on 2019-09-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20190910_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name_plural': 'Pictures'},
        ),
        migrations.AlterModelOptions(
            name='trabajos',
            options={'verbose_name_plural': 'Trabajos'},
        ),
    ]
