# Generated by Django 2.2.5 on 2019-09-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20190910_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajos',
            name='pictures',
        ),
        migrations.AddField(
            model_name='trabajos',
            name='pictures',
            field=models.ManyToManyField(help_text='Cargar y seleccionar las imagenes...', to='catalogo.Pictures'),
        ),
    ]
