# Generated by Django 2.2.5 on 2019-09-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20190910_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajos',
            options={'ordering': ['-fecha_publicado'], 'verbose_name_plural': 'Trabajos'},
        ),
    ]
