# Generated by Django 2.2.4 on 2019-09-17 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20190912_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.Autor'),
        ),
    ]
