# Generated by Django 2.2.5 on 2019-09-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_pictures_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('fecha_publicado', models.DateTimeField(auto_now_add=True)),
                ('genero', models.ManyToManyField(help_text='Género o técnica empleada...', to='catalogo.Genero')),
            ],
            options={
                'ordering': ['-fecha_publicado'],
            },
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='trabajos',
            name='pictures',
        ),
        migrations.AddField(
            model_name='pictures',
            name='year',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.Autores'),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='trabajos',
        ),
    ]
